create table if not exists progreso (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  mood text not null,
  tareas jsonb not null default '[]'::jsonb,
  completado boolean not null default false,
  fecha_actualizacion date not null default current_date,
  unique (usuario_id, mood)
);

alter table progreso enable row level security;

create policy "usuarios ven su progreso"
on progreso
for select
using (auth.uid() = usuario_id);

create policy "usuarios crean su progreso"
on progreso
for insert
with check (auth.uid() = usuario_id);

create policy "usuarios actualizan su progreso"
on progreso
for update
using (auth.uid() = usuario_id)
with check (auth.uid() = usuario_id);
